export {default as Header} from "./Header"
export {default as Home} from "./Home"
export {default as About} from "./About"
export {default as Contact} from "./Contact"
export {default as Skills} from "./Skills"
export {default as Footer} from "./Footer"
export {default as Greeting} from './greeting/Greeting.jsx'
export {default as Projects} from './project/Projects.jsx'
export {default as ProjectCard} from './project/ProjectCard.jsx'